name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: laasya_2279
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_recent: 2

  music:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.music.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/track/5pXui9rkf5W90DgZobuDiK
          plugin_music_limit: 1
